-- Migration: campuses and program-campus offerings become database-managed
-- instead of hardcoded in the app, so they can be validated/edited from a
-- dedicated "Campus Validation" tab (add campuses, add programs, and mark
-- which campuses offer which program).

create table if not exists campuses (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz default now()
);
create unique index if not exists campuses_name_unique on campuses (name);

create table if not exists program_campuses (
  id bigint generated by default as identity primary key,
  program_id bigint not null references programs(id) on delete cascade,
  campus_id bigint not null references campuses(id) on delete cascade,
  created_at timestamptz default now()
);
create unique index if not exists program_campuses_unique on program_campuses (program_id, campus_id);

-- Seed the campus list from the previously hardcoded PSU_CAMPUSES constant.
-- Program-campus offerings are not seeded here (the old mapping matched
-- program names by fuzzy fragment, which doesn't translate cleanly to
-- program_id rows) — configure those from the Campus Validation tab instead.
insert into campuses (name) values
  ('Main Campus'), ('PSU-PCAT CUYO'), ('PSU-ARACELI'), ('PSU-BALABAC'),
  ('PSU-BATARAZA'), ('PSU-BROOKES POINT'), ('PSU-CORON'), ('PSU-DUMARAN'),
  ('PSU-EL NIDO'), ('PSU-LINAPACAN'), ('PSU-NARRA'), ('PSU-QUEZON'),
  ('PSU-RIZAL'), ('PSU-ROXAS'), ('PSU-SAN VICENTE'), ('PSU-SOFRONIO ESPANOLA'),
  ('PSU-TAYTAY'), ('Manalo Campus')
on conflict (name) do nothing;
