-- One-shot migration that brings any older database to current schema.
-- Safe to re-run; every statement is idempotent. Non-destructive: all
-- existing programs, subjects, titles, and assignments are kept.
--
-- Equivalent to running 02_resource_types.sql + 03_title_campus.sql +
-- 04_curriculum_only_programs.sql + 05_campus_program_management.sql +
-- 06_title_embeddings.sql + 07_title_barcodes.sql + 08_titles_fulltext_search.sql +
-- 09_institutional_repository.sql + 10_subject_lock.sql + 11_activity_log.sql +
-- 12_procurement_cost_estimate.sql + 13_roles_and_permissions.sql +
-- 14_supplier_offers.sql + 15_supplier_offer_batches.sql +
-- 16_user_campus_scope.sql + 17_sync_jobs.sql + 18_complementary_and_provider.sql +
-- 19_unmatched_titles_function.sql + 20_fix_unmatched_titles_count.sql +
-- 21_faculty_role.sql + 22_purchase_request_records.sql +
-- 23_purchase_request_campus.sql + 24_pr_workflow.sql +
-- 25_campus_budgets.sql + 26_pr_cancel_and_po.sql +
-- 27_purchase_order_lifecycle.sql + 28_title_recommendations.sql in
-- order. If you've already run some of those individually, running this
-- on top is still safe.

-- ---------------------------------------------------------------------------
-- 02: expanded resource types + ISSN
-- ---------------------------------------------------------------------------
alter table titles drop constraint if exists titles_format_check;

alter table titles add column if not exists issn text default '';
create index if not exists titles_issn_idx on titles (issn);

update titles set format = 'ebook_paid'   where format = 'ebook';
update titles set format = 'book_printed' where format = 'printed';

alter table titles add constraint titles_format_check check (format in (
  'ebook_paid', 'ebook_open',
  'book_printed',
  'journal_printed',
  'journal_online_paid', 'journal_online_open'
));

-- ---------------------------------------------------------------------------
-- 03: campus column on printed titles
-- ---------------------------------------------------------------------------
alter table titles add column if not exists campus text default '';
create index if not exists titles_campus_idx on titles (campus);

-- ---------------------------------------------------------------------------
-- 04: programs are curriculum-only (no campus/college/section)
-- ---------------------------------------------------------------------------
drop index if exists programs_unique;
alter table programs drop column if exists campus;
alter table programs drop column if exists college;
alter table subjects drop column if exists section;
create unique index if not exists programs_unique on programs (name);

-- ---------------------------------------------------------------------------
-- 05: campuses + program-campus offerings become database-managed
-- ---------------------------------------------------------------------------
create table if not exists campuses (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz default now()
);
create unique index if not exists campuses_name_unique on campuses (name);

create table if not exists program_campuses (
  id bigint generated by default as identity primary key,
  program_id bigint not null references programs(id) on delete cascade,
  campus_id bigint not null references campuses(id) on delete cascade,
  created_at timestamptz default now()
);
create unique index if not exists program_campuses_unique on program_campuses (program_id, campus_id);

insert into campuses (name) values
  ('Main Campus'), ('PSU-PCAT CUYO'), ('PSU-ARACELI'), ('PSU-BALABAC'),
  ('PSU-BATARAZA'), ('PSU-BROOKES POINT'), ('PSU-CORON'), ('PSU-DUMARAN'),
  ('PSU-EL NIDO'), ('PSU-LINAPACAN'), ('PSU-NARRA'), ('PSU-QUEZON'),
  ('PSU-RIZAL'), ('PSU-ROXAS'), ('PSU-SAN VICENTE'), ('PSU-SOFRONIO ESPANOLA'),
  ('PSU-TAYTAY'), ('Manalo Campus')
on conflict (name) do nothing;

-- ---------------------------------------------------------------------------
-- 06: cached title embeddings for hybrid (BM25 + semantic) matching
-- ---------------------------------------------------------------------------
alter table titles add column if not exists embedding jsonb;

-- ---------------------------------------------------------------------------
-- 07: track counted barcodes so repeat catalog uploads don't double-count
-- ---------------------------------------------------------------------------
alter table titles add column if not exists barcodes jsonb default '[]'::jsonb;

-- ---------------------------------------------------------------------------
-- 08: full-text search index for scalable matching (500k+ row catalogs)
-- NOTE: on a large catalog, run this section's statements SEPARATELY (see
-- supabase/migrations/08_titles_fulltext_search.sql for the split-out,
-- copy-pasteable version) -- combined here only for smaller/fresh databases.
-- ---------------------------------------------------------------------------
set statement_timeout = '15min';

alter table titles add column if not exists search_vector tsvector
  generated always as (
    to_tsvector('english',
      coalesce(title, '') || ' ' ||
      coalesce(author, '') || ' ' ||
      coalesce(publisher, '') || ' ' ||
      coalesce(subjects, '')
    )
  ) stored;

create index if not exists titles_search_idx on titles using gin (search_vector);

create or replace function match_titles_candidates(query_text text, must_text text, limit_n int)
returns table (
  id bigint,
  format text,
  title text,
  author text,
  publisher text,
  year text,
  subjects text,
  embedding jsonb,
  lexical_rank real,
  is_must_match boolean
)
language sql stable
set statement_timeout = '30s'
as $$
  with must_matches as (
    select t.id, ts_rank_cd(t.search_vector, to_tsquery('english', must_text)) as lexical_rank, true as is_must
    from titles t
    where must_text is not null and must_text <> ''
      and t.search_vector @@ to_tsquery('english', must_text)
    limit 20000
  ),
  broad_matches as (
    select t.id, ts_rank_cd(t.search_vector, to_tsquery('english', query_text)) as lexical_rank, false as is_must
    from titles t
    where t.search_vector @@ to_tsquery('english', query_text)
    limit greatest(limit_n * 20, 6000)
  ),
  grouped as (
    select id, max(lexical_rank) as lexical_rank, bool_or(is_must) as is_must_match
    from (select * from must_matches union all select * from broad_matches) combined
    group by id
  )
  select t.id, t.format, t.title, t.author, t.publisher, t.year, t.subjects, t.embedding,
         g.lexical_rank, g.is_must_match
  from grouped g
  join titles t on t.id = g.id
  order by g.is_must_match desc, g.lexical_rank desc
  limit limit_n;
$$;

drop function if exists match_titles_candidates(text, int);

-- ---------------------------------------------------------------------------
-- 09: institutional_repository title format
-- ---------------------------------------------------------------------------
alter table titles drop constraint if exists titles_format_check;

alter table titles add constraint titles_format_check check (format in (
  'ebook_paid', 'ebook_open',
  'book_printed',
  'journal_printed',
  'journal_online_paid', 'journal_online_open',
  'institutional_repository'
));

-- ---------------------------------------------------------------------------
-- 10: per-subject lock, so a curated title list survives future Match runs
-- ---------------------------------------------------------------------------
alter table subjects add column if not exists locked boolean not null default false;

-- ---------------------------------------------------------------------------
-- 11: activity log + upload-batch tracking for revert
-- ---------------------------------------------------------------------------
alter table titles   add column if not exists batch_id uuid;
alter table subjects add column if not exists batch_id uuid;
create index if not exists titles_batch_idx   on titles (batch_id);
create index if not exists subjects_batch_idx on subjects (batch_id);

create table if not exists activity_log (
  id          bigserial primary key,
  created_at  timestamptz default now(),
  user_email  text default '',
  action      text not null,
  summary     text not null,
  detail      jsonb default '{}'::jsonb,
  batch_id    uuid,
  revertible  boolean default false,
  reverted_at timestamptz
);
create index if not exists activity_log_created_idx on activity_log (created_at desc);
create index if not exists activity_log_batch_idx   on activity_log (batch_id);

alter table activity_log enable row level security;

-- ---------------------------------------------------------------------------
-- 12: per-program / per-subject procurement cost-per-title estimates
-- ---------------------------------------------------------------------------
alter table programs add column if not exists cost_per_title numeric;
alter table subjects add column if not exists cost_per_title numeric;

-- ---------------------------------------------------------------------------
-- 13: admin-configurable roles and per-tab view/edit permissions
-- ---------------------------------------------------------------------------
create table if not exists roles (
  id bigserial primary key,
  name text not null unique,
  is_admin boolean not null default false,
  created_at timestamptz default now()
);

create table if not exists role_tab_permissions (
  role_id bigint not null references roles(id) on delete cascade,
  tab_id text not null,
  can_view boolean not null default false,
  can_edit boolean not null default false,
  primary key (role_id, tab_id)
);

create table if not exists user_roles (
  email text primary key,
  role_id bigint not null references roles(id) on delete cascade,
  created_at timestamptz default now()
);

insert into roles (name, is_admin) values
  ('Admin', true),
  ('Librarian', false),
  ('Library Staff', false),
  ('Supplier', false)
on conflict (name) do nothing;

insert into user_roles (email, role_id)
select 'cbnalica@gmail.com', id from roles where name = 'Admin'
on conflict (email) do update set role_id = excluded.role_id;

insert into role_tab_permissions (role_id, tab_id, can_view, can_edit)
select r.id, t.tab_id, true, true
from roles r, (values
  ('upload'), ('match'), ('programs'), ('campus-validation'),
  ('procurement'), ('canvassing'), ('purchase-request'), ('activity')
) as t(tab_id)
where r.name = 'Librarian'
on conflict (role_id, tab_id) do nothing;

insert into role_tab_permissions (role_id, tab_id, can_view, can_edit)
select r.id, t.tab_id, true, true
from roles r, (values
  ('upload'), ('match'), ('programs'), ('campus-validation'),
  ('procurement'), ('canvassing'), ('purchase-request')
) as t(tab_id)
where r.name = 'Library Staff'
on conflict (role_id, tab_id) do nothing;

insert into role_tab_permissions (role_id, tab_id, can_view, can_edit)
select r.id, 'activity', true, false
from roles r where r.name = 'Library Staff'
on conflict (role_id, tab_id) do nothing;

insert into role_tab_permissions (role_id, tab_id, can_view, can_edit)
select r.id, 'supplier-view', true, false
from roles r where r.name = 'Supplier'
on conflict (role_id, tab_id) do nothing;

alter table roles enable row level security;
alter table role_tab_permissions enable row level security;
alter table user_roles enable row level security;

-- ---------------------------------------------------------------------------
-- 14: supplier offer submissions
-- ---------------------------------------------------------------------------
create table if not exists supplier_offers (
  id           bigserial primary key,
  subject_id   bigint references subjects(id) on delete set null,
  supplier_email text not null,
  title        text not null,
  author       text default '',
  format       text default '',
  price        numeric,
  notes        text default '',
  status       text not null default 'pending' check (status in ('pending', 'accepted', 'declined')),
  created_at   timestamptz default now(),
  decided_at   timestamptz,
  decided_by   text default ''
);
create index if not exists supplier_offers_subject_idx on supplier_offers (subject_id);
create index if not exists supplier_offers_status_idx  on supplier_offers (status);
create index if not exists supplier_offers_email_idx   on supplier_offers (supplier_email);

alter table supplier_offers enable row level security;

update role_tab_permissions
set can_edit = true
where tab_id = 'supplier-view'
  and role_id in (select id from roles where name = 'Supplier');

-- ---------------------------------------------------------------------------
-- 15: supplier offer batches
-- ---------------------------------------------------------------------------
alter table supplier_offers add column if not exists batch_id uuid;
create index if not exists supplier_offers_batch_idx on supplier_offers (batch_id);

-- ---------------------------------------------------------------------------
-- 16: per-user campus scope
-- ---------------------------------------------------------------------------
create table if not exists user_campuses (
  email      text not null,
  campus_id  bigint not null references campuses(id) on delete cascade,
  created_at timestamptz default now(),
  primary key (email, campus_id)
);
create index if not exists user_campuses_email_idx on user_campuses (email);

-- ---------------------------------------------------------------------------
-- 17: resumable background sync jobs
-- ---------------------------------------------------------------------------
create table if not exists sync_jobs (
  id                uuid primary key,
  kind              text not null,
  status            text not null default 'running',
  total             int not null default 0,
  inserted          int not null default 0,
  updated           int not null default 0,
  duplicates        int not null default 0,
  no_campus_titles  jsonb not null default '[]'::jsonb,
  unmapped_campuses jsonb not null default '[]'::jsonb,
  error             text,
  batch_id          uuid,
  created_by        text default '',
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create index if not exists sync_jobs_kind_created_idx on sync_jobs (kind, created_at desc);

create table if not exists sync_job_items (
  id     bigserial primary key,
  job_id uuid not null references sync_jobs(id) on delete cascade,
  seq    int not null,
  op     jsonb not null
);
create index if not exists sync_job_items_job_seq_idx on sync_job_items (job_id, seq);

alter table sync_jobs enable row level security;
alter table sync_job_items enable row level security;

-- ---------------------------------------------------------------------------
-- 18: complementary eBook/journal formats + provider column
-- ---------------------------------------------------------------------------
alter table titles drop constraint if exists titles_format_check;

alter table titles add constraint titles_format_check check (format in (
  'ebook_paid', 'ebook_open', 'ebook_complementary',
  'book_printed',
  'journal_printed',
  'journal_online_paid', 'journal_online_open', 'journal_complementary',
  'institutional_repository'
));

alter table titles add column if not exists provider text default '';

-- ---------------------------------------------------------------------------
-- 19+20: unmatched_titles_batch()/unmatched_titles_count() helpers for
-- migrating never-matched titles. unmatched_titles_count is written as a
-- subtraction of two cheap counts rather than a direct anti-join COUNT --
-- unlike the batch function, a COUNT can't stop early via LIMIT, so
-- computing it the naive way is slow enough on a 500k+ row table to hit
-- Supabase's statement timeout.
-- ---------------------------------------------------------------------------
create or replace function unmatched_titles_batch(p_format text, batch_size int)
returns table (
  id bigint, title text, author text, publisher text, year text,
  isbn text, url text, subjects text, provider text
)
language sql stable
set statement_timeout = '25s'
as $$
  select t.id, t.title, t.author, t.publisher, t.year, t.isbn, t.url, t.subjects, t.provider
  from titles t
  where t.format = p_format
    and not exists (select 1 from assignments a where a.title_id = t.id)
  order by t.id
  limit batch_size;
$$;

create or replace function unmatched_titles_count(p_format text)
returns bigint
language sql stable
set statement_timeout = '25s'
as $$
  select
    (select count(*) from titles t where t.format = p_format)
    -
    (select count(distinct a.title_id)
     from assignments a
     join titles t on t.id = a.title_id
     where t.format = p_format);
$$;

-- ---------------------------------------------------------------------------
-- 21: "Faculty Member" role, auto-granted on first Google SSO sign-in from
-- the university's domain -- see app/api/auth/provision-google. No default
-- tab permissions: starts at zero access like any unassigned email, until
-- an admin grants specific tabs from User Management.
-- ---------------------------------------------------------------------------
insert into roles (name, is_admin) values
  ('Faculty Member', false)
on conflict (name) do nothing;

-- ---------------------------------------------------------------------------
-- 22: persisted Purchase Request records, so the Monitoring tab can list
-- them. /api/purchase-request still also streams back the .xlsx download.
-- ---------------------------------------------------------------------------
create table if not exists purchase_requests (
  id bigserial primary key,
  pr_no text not null default '',
  submitted_by text not null default '',
  entity_name text default '',
  office text default '',
  fund_cluster text default '',
  rc_code text default '',
  purpose text default '',
  requested_by text default '',
  approved_by text default '',
  pr_date text default '',
  items jsonb not null default '[]'::jsonb,
  total_amount numeric not null default 0,
  created_at timestamptz default now()
);

create index if not exists purchase_requests_created_at_idx on purchase_requests(created_at desc);

alter table purchase_requests enable row level security;

-- ---------------------------------------------------------------------------
-- 23: attribute each Purchase Request to a campus, for Monitoring's
-- per-campus grouping and budget-vs-spent comparison.
-- ---------------------------------------------------------------------------
alter table purchase_requests add column if not exists campus text default '';
alter table purchase_requests add column if not exists campus_id bigint references campuses(id) on delete set null;

create index if not exists purchase_requests_campus_id_idx on purchase_requests(campus_id);

-- ---------------------------------------------------------------------------
-- 24: admin-configurable PR approval workflow (offices a PR passes
-- through) + per-PR current-step tracking + step history, so Monitoring
-- can flag a PR pending 15+ days in the same office.
-- ---------------------------------------------------------------------------
create table if not exists pr_workflow_steps (
  id bigserial primary key,
  seq int not null unique,
  office_name text not null,
  created_at timestamptz default now()
);

alter table purchase_requests add column if not exists current_step_seq int;
alter table purchase_requests add column if not exists step_entered_at timestamptz default now();
alter table purchase_requests add column if not exists status text not null default 'in_progress';
alter table purchase_requests drop constraint if exists purchase_requests_status_check;
alter table purchase_requests add constraint purchase_requests_status_check
  check (status in ('in_progress', 'completed'));
alter table purchase_requests add column if not exists completed_at timestamptz;

create table if not exists pr_step_history (
  id bigserial primary key,
  purchase_request_id bigint not null references purchase_requests(id) on delete cascade,
  seq int not null,
  office_name text not null,
  entered_at timestamptz not null default now(),
  left_at timestamptz,
  moved_by text default '',
  notes text default ''
);
create index if not exists pr_step_history_pr_idx on pr_step_history(purchase_request_id);

alter table pr_workflow_steps enable row level security;
alter table pr_step_history enable row level security;

-- ---------------------------------------------------------------------------
-- 25: per-campus budget tracking. "Spent" is computed on read from
-- purchase_requests.total_amount, not stored here.
-- ---------------------------------------------------------------------------
create table if not exists campus_budgets (
  id bigserial primary key,
  campus_id bigint not null references campuses(id) on delete cascade,
  period text not null,
  amount numeric not null default 0,
  updated_at timestamptz default now(),
  updated_by text default ''
);
create unique index if not exists campus_budgets_unique on campus_budgets(campus_id, period);

alter table campus_budgets enable row level security;

-- ---------------------------------------------------------------------------
-- 26: Purchase Request cancellation + Purchase Orders (per-supplier
-- consolidation document generation).
-- ---------------------------------------------------------------------------
alter table purchase_requests drop constraint if exists purchase_requests_status_check;
alter table purchase_requests add constraint purchase_requests_status_check
  check (status in ('in_progress', 'completed', 'cancelled'));
alter table purchase_requests add column if not exists cancelled_at timestamptz;

create table if not exists purchase_orders (
  id bigserial primary key,
  po_no text not null default '',
  trans_no text default '',
  philgeps_ref_no text default '',
  supplier text not null default '',
  address text default '',
  tin text default '',
  mode_of_procurement text default '',
  place_of_delivery text default '',
  delivery_term text default '',
  date_of_delivery text default '',
  payment_term text default '',
  fund_cluster text default '',
  ors_burs_no text default '',
  date_of_ors_burs text default '',
  po_date text default '',
  items jsonb not null default '[]'::jsonb,
  total_amount numeric not null default 0,
  generated_by text not null default '',
  created_at timestamptz default now()
);
create index if not exists purchase_orders_created_at_idx on purchase_orders(created_at desc);
create index if not exists purchase_orders_supplier_idx on purchase_orders(supplier);

alter table purchase_orders enable row level security;

-- ---------------------------------------------------------------------------
-- 27: Purchase Orders gain a status/cancel lifecycle, same as Purchase
-- Requests -- lets a PO be edited or cancelled, and cancelling frees its
-- items back up for a future PO.
-- ---------------------------------------------------------------------------
alter table purchase_orders add column if not exists status text not null default 'active';
alter table purchase_orders drop constraint if exists purchase_orders_status_check;
alter table purchase_orders add constraint purchase_orders_status_check
  check (status in ('active', 'cancelled'));
alter table purchase_orders add column if not exists cancelled_at timestamptz;

-- ---------------------------------------------------------------------------
-- 28: faculty-submitted title recommendations per subject, and the default
-- tab grant that makes the Faculty Member role actually usable out of the
-- box.
-- ---------------------------------------------------------------------------
create table if not exists title_recommendations (
  id bigserial primary key,
  subject_id bigint not null references subjects(id) on delete cascade,
  recommended_by text not null default '',
  title text not null,
  author text default '',
  publisher text default '',
  year text default '',
  isbn text default '',
  format_preference text default '',
  notes text default '',
  status text not null default 'pending',
  created_at timestamptz default now()
);
alter table title_recommendations drop constraint if exists title_recommendations_status_check;
alter table title_recommendations add constraint title_recommendations_status_check
  check (status in ('pending', 'sourced', 'declined'));
create index if not exists title_recommendations_subject_idx on title_recommendations(subject_id);

alter table title_recommendations enable row level security;

insert into role_tab_permissions (role_id, tab_id, can_view, can_edit)
select r.id, 'faculty-recommendations', true, true
from roles r where r.name = 'Faculty Member'
on conflict (role_id, tab_id) do nothing;

-- ---------------------------------------------------------------------------
-- 29: let one canvassed/purchased title count toward more than one course's
-- compliance gap, and let a Purchase Request that isn't tied to one
-- physical campus (typically ebook-only requests) still be tracked against
-- a budget instead of disappearing from Monitoring's spend totals.
-- ---------------------------------------------------------------------------
create table if not exists canvassing_subjects (
  id            bigserial primary key,
  canvassing_id bigint not null references canvassing(id) on delete cascade,
  subject_id    bigint not null references subjects(id) on delete cascade,
  created_at    timestamptz default now()
);
create unique index if not exists canvassing_subjects_unique on canvassing_subjects(canvassing_id, subject_id);
create index if not exists canvassing_subjects_subject_idx on canvassing_subjects(subject_id);

insert into canvassing_subjects (canvassing_id, subject_id)
select id, subject_id from canvassing where subject_id is not null
on conflict (canvassing_id, subject_id) do nothing;

alter table canvassing_subjects enable row level security;
do $$ begin
  create policy "anon read canvassing_subjects" on canvassing_subjects for select using (true);
exception when duplicate_object then null; end $$;

alter table campus_budgets alter column campus_id drop not null;
create unique index if not exists campus_budgets_university_wide_unique
  on campus_budgets(period) where campus_id is null;

-- ---------------------------------------------------------------------------
-- 30: let a faculty title recommendation carry forward a link to an
-- already-canvassed/priced title, when added from the Faculty
-- Recommendations tab's "browse what's already been canvassed" list
-- instead of typed in from scratch.
-- ---------------------------------------------------------------------------
alter table title_recommendations add column if not exists canvassing_id bigint references canvassing(id) on delete set null;
create index if not exists title_recommendations_canvassing_idx on title_recommendations(canvassing_id);
