-- One-shot migration that brings any older database to current schema.
-- Safe to re-run; every statement is idempotent. Non-destructive: all
-- existing programs, subjects, titles, and assignments are kept.
--
-- Equivalent to running 02_resource_types.sql + 03_title_campus.sql +
-- 04_curriculum_only_programs.sql + 05_campus_program_management.sql +
-- 06_title_embeddings.sql + 07_title_barcodes.sql + 08_titles_fulltext_search.sql +
-- 09_institutional_repository.sql + 10_subject_lock.sql in order. If you've
-- already run some of those individually, running this on top is still safe.

-- ---------------------------------------------------------------------------
-- 02: expanded resource types + ISSN
-- ---------------------------------------------------------------------------
alter table titles drop constraint if exists titles_format_check;

alter table titles add column if not exists issn text default '';
create index if not exists titles_issn_idx on titles (issn);

update titles set format = 'ebook_paid'   where format = 'ebook';
update titles set format = 'book_printed' where format = 'printed';

alter table titles add constraint titles_format_check check (format in (
  'ebook_paid', 'ebook_open',
  'book_printed',
  'journal_printed',
  'journal_online_paid', 'journal_online_open'
));

-- ---------------------------------------------------------------------------
-- 03: campus column on printed titles
-- ---------------------------------------------------------------------------
alter table titles add column if not exists campus text default '';
create index if not exists titles_campus_idx on titles (campus);

-- ---------------------------------------------------------------------------
-- 04: programs are curriculum-only (no campus/college/section)
-- ---------------------------------------------------------------------------
drop index if exists programs_unique;
alter table programs drop column if exists campus;
alter table programs drop column if exists college;
alter table subjects drop column if exists section;
create unique index if not exists programs_unique on programs (name);

-- ---------------------------------------------------------------------------
-- 05: campuses + program-campus offerings become database-managed
-- ---------------------------------------------------------------------------
create table if not exists campuses (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz default now()
);
create unique index if not exists campuses_name_unique on campuses (name);

create table if not exists program_campuses (
  id bigint generated by default as identity primary key,
  program_id bigint not null references programs(id) on delete cascade,
  campus_id bigint not null references campuses(id) on delete cascade,
  created_at timestamptz default now()
);
create unique index if not exists program_campuses_unique on program_campuses (program_id, campus_id);

insert into campuses (name) values
  ('Main Campus'), ('PSU-PCAT CUYO'), ('PSU-ARACELI'), ('PSU-BALABAC'),
  ('PSU-BATARAZA'), ('PSU-BROOKES POINT'), ('PSU-CORON'), ('PSU-DUMARAN'),
  ('PSU-EL NIDO'), ('PSU-LINAPACAN'), ('PSU-NARRA'), ('PSU-QUEZON'),
  ('PSU-RIZAL'), ('PSU-ROXAS'), ('PSU-SAN VICENTE'), ('PSU-SOFRONIO ESPANOLA'),
  ('PSU-TAYTAY'), ('Manalo Campus')
on conflict (name) do nothing;

-- ---------------------------------------------------------------------------
-- 06: cached title embeddings for hybrid (BM25 + semantic) matching
-- ---------------------------------------------------------------------------
alter table titles add column if not exists embedding jsonb;

-- ---------------------------------------------------------------------------
-- 07: track counted barcodes so repeat catalog uploads don't double-count
-- ---------------------------------------------------------------------------
alter table titles add column if not exists barcodes jsonb default '[]'::jsonb;

-- ---------------------------------------------------------------------------
-- 08: full-text search index for scalable matching (500k+ row catalogs)
-- NOTE: on a large catalog, run this section's statements SEPARATELY (see
-- supabase/migrations/08_titles_fulltext_search.sql for the split-out,
-- copy-pasteable version) -- combined here only for smaller/fresh databases.
-- ---------------------------------------------------------------------------
set statement_timeout = '15min';

alter table titles add column if not exists search_vector tsvector
  generated always as (
    to_tsvector('english',
      coalesce(title, '') || ' ' ||
      coalesce(author, '') || ' ' ||
      coalesce(publisher, '') || ' ' ||
      coalesce(subjects, '')
    )
  ) stored;

create index if not exists titles_search_idx on titles using gin (search_vector);

create or replace function match_titles_candidates(query_text text, limit_n int)
returns table (
  id bigint,
  format text,
  title text,
  author text,
  publisher text,
  year text,
  subjects text,
  embedding jsonb,
  lexical_rank real
)
language sql stable
as $$
  select sub.id, sub.format, sub.title, sub.author, sub.publisher, sub.year, sub.subjects,
         sub.embedding, ts_rank_cd(sub.search_vector, to_tsquery('english', query_text)) as lexical_rank
  from (
    select t.id, t.format, t.title, t.author, t.publisher, t.year, t.subjects,
           t.embedding, t.search_vector
    from titles t
    where t.search_vector @@ to_tsquery('english', query_text)
    limit greatest(limit_n * 20, 3000)
  ) sub
  order by lexical_rank desc
  limit limit_n;
$$;

-- ---------------------------------------------------------------------------
-- 09: institutional_repository title format
-- ---------------------------------------------------------------------------
alter table titles drop constraint if exists titles_format_check;

alter table titles add constraint titles_format_check check (format in (
  'ebook_paid', 'ebook_open',
  'book_printed',
  'journal_printed',
  'journal_online_paid', 'journal_online_open',
  'institutional_repository'
));

-- ---------------------------------------------------------------------------
-- 10: per-subject lock, so a curated title list survives future Match runs
-- ---------------------------------------------------------------------------
alter table subjects add column if not exists locked boolean not null default false;
